-- Baseline migration for the Mantenimiento domain (Joaquín).
--
-- These tables (actividad, intervencion, intervencion_insumo, orden_trabajo,
-- tarea_ot, umbral_mantenimiento) already existed in the database — they were
-- applied via `prisma db push` and were never captured by a tracked
-- migration. This migration does NOT create them (they already exist); it
-- exists only so `prisma migrate status` has a clean baseline to diff future
-- schema changes against. It is registered via
-- `prisma migrate resolve --applied` rather than executed.
--
-- Generated by diffing prisma/migrations (as tracked before this baseline)
-- against the live database with `prisma migrate diff`.

-- CreateEnum
CREATE TYPE "public"."EstadoActividad" AS ENUM ('PENDIENTE', 'COMPLETADA');

-- CreateEnum
CREATE TYPE "public"."EstadoOT" AS ENUM ('PENDIENTE', 'ASIGNADA', 'EN_PROCESO', 'COMPLETADA', 'CANCELADA');

-- CreateEnum
CREATE TYPE "public"."OrigenActividad" AS ENUM ('HALLAZGO', 'EQUIPO', 'MANUAL');

-- CreateEnum
CREATE TYPE "public"."OrigenOT" AS ENUM ('MANUAL', 'PREVENTIVO', 'HALLAZGO');

-- CreateEnum
CREATE TYPE "public"."PrioridadOT" AS ENUM ('BAJA', 'MEDIA', 'ALTA', 'CRITICA');

-- CreateEnum
CREATE TYPE "public"."TipoOT" AS ENUM ('CORRECTIVA', 'PREVENTIVA');

-- CreateTable
CREATE TABLE "public"."actividad" (
    "id" TEXT NOT NULL,
    "descripcion" TEXT NOT NULL,
    "origen" "public"."OrigenActividad" NOT NULL DEFAULT 'MANUAL',
    "referencia" TEXT,
    "asignadoAId" TEXT,
    "equipoId" TEXT,
    "hallazgoId" TEXT,
    "estado" "public"."EstadoActividad" NOT NULL DEFAULT 'PENDIENTE',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "actividad_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."intervencion" (
    "id" TEXT NOT NULL,
    "ordenId" TEXT NOT NULL,
    "tipo" "public"."TipoOT" NOT NULL DEFAULT 'CORRECTIVA',
    "detalle" TEXT NOT NULL,
    "horasHombre" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "horometro" DOUBLE PRECISION,
    "realizadaPorId" TEXT,
    "soloLectura" BOOLEAN NOT NULL DEFAULT false,
    "fecha" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "intervencion_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."intervencion_insumo" (
    "id" TEXT NOT NULL,
    "intervencionId" TEXT NOT NULL,
    "insumoId" TEXT NOT NULL,
    "cantidad" INTEGER NOT NULL,

    CONSTRAINT "intervencion_insumo_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."orden_trabajo" (
    "id" TEXT NOT NULL,
    "equipoId" TEXT NOT NULL,
    "asignadoAId" TEXT,
    "titulo" TEXT NOT NULL,
    "estado" "public"."EstadoOT" NOT NULL DEFAULT 'PENDIENTE',
    "prioridad" "public"."PrioridadOT" NOT NULL DEFAULT 'MEDIA',
    "tipo" "public"."TipoOT" NOT NULL DEFAULT 'CORRECTIVA',
    "origen" "public"."OrigenOT" NOT NULL DEFAULT 'MANUAL',
    "origenDetalle" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "orden_trabajo_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."tarea_ot" (
    "id" TEXT NOT NULL,
    "ordenId" TEXT NOT NULL,
    "texto" TEXT NOT NULL,
    "hecha" BOOLEAN NOT NULL DEFAULT false,
    "posicion" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "tarea_ot_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."umbral_mantenimiento" (
    "id" TEXT NOT NULL,
    "tipoEquipo" TEXT NOT NULL,
    "tipoMantencion" TEXT NOT NULL,
    "umbralHoras" INTEGER NOT NULL,

    CONSTRAINT "umbral_mantenimiento_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "intervencion_ordenId_idx" ON "public"."intervencion"("ordenId" ASC);

-- CreateIndex
CREATE INDEX "intervencion_insumo_intervencionId_idx" ON "public"."intervencion_insumo"("intervencionId" ASC);

-- CreateIndex
CREATE INDEX "orden_trabajo_equipoId_idx" ON "public"."orden_trabajo"("equipoId" ASC);

-- CreateIndex
CREATE INDEX "orden_trabajo_estado_idx" ON "public"."orden_trabajo"("estado" ASC);

-- CreateIndex
CREATE INDEX "tarea_ot_ordenId_idx" ON "public"."tarea_ot"("ordenId" ASC);

-- AddForeignKey
ALTER TABLE "public"."intervencion" ADD CONSTRAINT "intervencion_ordenId_fkey" FOREIGN KEY ("ordenId") REFERENCES "public"."orden_trabajo"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."intervencion_insumo" ADD CONSTRAINT "intervencion_insumo_intervencionId_fkey" FOREIGN KEY ("intervencionId") REFERENCES "public"."intervencion"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."tarea_ot" ADD CONSTRAINT "tarea_ot_ordenId_fkey" FOREIGN KEY ("ordenId") REFERENCES "public"."orden_trabajo"("id") ON DELETE CASCADE ON UPDATE CASCADE;
